text = {
    'start_command'                 : 'شروع کار با ربات',
    'help_command'                  : 'راهنمای کار با ربات',
    'support_command'               : 'ارتباط با پشتیبانی',
    'support_request'               : 'برای پاسخ به این پیام کلیک نمایید',
    'support_message'               : 'پاسخ خود را بنویسید',
    'support_answered'              : 'پاسخ با موفقیت برای کاربر ارسال شد',
    'support_another_admin'         : 'این پیام توسط ادمین دیگر پاسخ داده شد',
    'hidden_user_reply'             : 'امکان ارسال پیام وجود ندارد، از دکمه پاسخ استفاده نمایید',
    'quiz_creating_command'         : 'شروع کوئیز',
    'exam_creating_command'         : 'شروع آزمون',
    'show_categories'               : 'مشاهده موضوعات',
    'add_question_teacher'          : 'اضافه کردن یک سوال',
    'add_question_teacher_mul'      : 'اضافه کردن چند سوال با فایل .xlsx',
    'add_teacher_admin'             : 'اضافه کردن معلم',
    'add_category_command'          : 'اضافه کردن موضوع',
    'add_category_admin'            : 'نام موضوع مورد نظر را وارد نمایید',
    'choice_category_admin'         : 'لطفا موضوع سوال خود را انتخاب نمایید',
    'add_question_admin_resp'       : 'می توانید سوال را ارسال نمایید',
    'photo_and_text_question'       : 'ابتدا صورت سوال را ارسال نمایید، یا یک متن بنویسید، یا عکسی با کپشن ارسال نمایید',
    'get_option1'                   : 'گزینه اول را وارد نمایید',
    'get_option2'                   : 'گزینه دوم را وارد نمایید',
    'get_option3'                   : 'گزینه سوم را وارد نمایید',
    'get_option4'                   : 'گزینه چهارم را وارد نمایید',
    'get_optionanswer'              : 'گزینه صحیح را وارد نمایید، به صورت عدد انگلیسی بین 1 تا 4',
    'get_textanswer'                : 'پاسخ تشریحی سوال را وارد کنید، یا به صورت متن یا به صورت یک عکس',
    'questoin_added'                : 'سوال مورد نظر در دیتابیس ذخیره شد',
    'request_teacher'               : 'درخواست دسترسی به پنل معلم',
    'buttons_choice'                : 'می توانید گزینه های زیر را انتخاب نمایید',
    'user_teacher_added'            : 'کاربر تایید صلاحیت شده است',
    'category_choice_callanswe'     : 'موضوع انتخاب شد',
    'options'                       : 'گزینه ها ',
    'get_answer_for_question'       : 'مشاهده پاسخ 💡',
    'delete_answer_text_photo'      : 'پاک کردن پاسخ 🗑️',
    'delete_question'               : 'پاک کردن سوال 🗑️',
    'report_question_designer'      : 'گزارش خطا در سوال یا پاسخ ⚠️',
    'report_wrong_question'         : 'لطفا مشکل سوال را به صورت دقیق در یک پیام ارسال کنید تا جهت بررسی برای طراح سوال ارسال شود.',
    'report_wrong_question_sended'  : 'پیام شما برای طراح سوال ارسال شد، با تشکر',
    # edit question 
    'edit_question_categoty'        : 'ویرایش موضوع 📝',
    'edit_question_text'            : 'ویرایش صورت سوال 📝',
    'edit_question_photo_id'        : 'ویرایش عکس سوال 📝',
    'edit_question_anstext'         : 'ویرایش متن پاسخ 📝',
    'edit_question_ansop'           : 'ویرایش گزینه صحیح 📝',
    'edit_question_op1'             : 'ویرایش گزینه اول 📝',
    'edit_question_op2'             : 'ویرایش گزینه دوم 📝',
    'edit_question_op3'             : 'ویرایش گزینه سوم 📝',
    'edit_question_op4'             : 'ویرایش گزینه چهارم 📝',
    'end_edit_question'             : 'اتمام ویرایش ✅',
    'get_new_category'              : 'موضوع جدید سوال را انتخاب نمایید',
    'get_new_text'                  : 'صورت سوال جدید را وارد نمایید',
    'get_new_ans_text'              : 'متن یا عکس جدید برای پاسخ سوال را ارسال نمایید',
    'get_new_ans_option'            : 'گزینه صحیح را وارد نمایید به صورت عدد انگلیسی بین 1 تا 4',
    'get_new_option'                : 'متن گزینه جدید را وارد نمایید',
    'get_new_photo'                 : 'عکس جدید صورت سوال را ارسال نمایید',
    'edited_successfully'           : 'سوال مورد نظر در دیتابیس آپدیت شد🟢',
    # teacher panel
    'teachpanel'                    : 'پنل معلم 💡',
    'enterteacherpanel'             : 'ورود به پنل معلم 🟢',
    'exitteacherpanel'              : 'خروج از پنل معلم 🔴',
    'entergeneralquizpanel'         : 'ورود به بخش کوئیز 🟢',
    'exitgeneralquizpanel'          : 'خروج از بخش کوئیز 🔴',
    'enterexampanel'                : 'ورود به بخش مدیریت آزمون ها 🟢',
    'exitexampanel'                 : 'خروج از بخش مدیریت آزمون ها 🔴',
    'entercreateexampanel'          : 'ورود به بخش ساخت آزمون جدید 🟢',
    'exitcreateexampanel'           : 'خروج از بخش ساخت آزمون جدید 🔴',
    'enterreportpanel'              : 'ورود به پنل کارنامه 🟢',
    'exitreportpanel'               : 'خروج از پنل کارنامه 🔴',
}



option_sticker = {
    '1' : '1️⃣',
    '2' : '2️⃣',
    '3' : '3️⃣',
    '4' : '4️⃣',
}

Button = {
    'start'                 : text['start_command']             + '💡',
    'help'                  : text['help_command']              + '❓',
    'quiz'                  : text['quiz_creating_command']     + '✖️➗',
    'exam'                  : text['exam_creating_command']     + '🧪',
    'support'               : text['support_command']           + '📞',
    'addquestion'           : text['add_question_teacher']      + '⚡',
    'addquestionmul'        : text['add_question_teacher_mul']  + '⚡',
    'addcategory'           : text['add_category_command']      + '⚡',
    'showcategory'          : text['show_categories']           + 'ℹ️',
    'req_teacher'           : text['request_teacher']           + '🧑‍🏫',
    'generalquizpanel'      : 'افزودن سوال به بخش کوئیز'      + '✅',
    'exammanagement'        : 'ورود به پنل مدیریت آزمون'      + '✅',
    'exitgeneralquizpanel'  : 'خروج از بخش کوئیز'             + '❌',
    'exitexammanagement'    : 'خروج از بخش مدیریت آزمون'      + '❌',
    # -------------
    'showexams'             : 'مشاهده آزمون ها 💡',
    'createexam'            : 'ساخت آزمون جدید  🧪',
    'exitcreateexam'        : 'خروج از پنل ساخت آزمون جدید ❌',
    # -------------
    'teacherpanel'          : text['teachpanel'],
    'exitteacherpanel'      : 'خروج از پنل معلم ❌',
    # ---------------
    'reportpanel'           : 'پنل کارنامه 📝',
    'exitreportpanel'       : 'خروج از پنل کارنامه ❌',
    'quizreport'            : 'مشاهده عملکرد در کوئیز ها 📝',
    'examreport'            : 'مشاهده عملکرد در آزمون ها 📝',
    # ---------------
}