text = {
    'start_command'             : 'شروع کار با ربات',
    'help_command'              : 'راهنمای نحوه کار با ربات',
    'support_command'           : 'ارتباط با پشتیبانی',
    'support_request'           : 'برای پاسخ به این پیام کلیک نمایید',
    'support_message'           : 'پاسخ خود را بنویسید',
    'support_answered'          : 'پاسخ با موفقیت برای کاربر ارسال شد',
    'support_another_admin'     : 'این پیام توسط ادمین دیگر پاسخ داده شد',
    'hidden_user_reply'         : 'امکان ارسال پیام وجود ندارد، از دکمه پاسخ استفاده نمایید',
    'quiz_creating_command'     : 'ساخت کوئیز',
    'show_categories'           : 'مشاهده موضوعات',
    'add_question_admin'        : 'اضافه کردن یک سوال',
    'add_category_command'      : 'اضافه کردن موضوع',
    'add_category_admin'        : 'نام موضوع مورد نظر را وارد نمایید',
    'choice_category_admin'     : 'لطفا موضوع سوال خود را انتخاب نمایید',
    'add_question_admin_resp'   : 'می توانید سوال را ارسال نمایید',
    'photo_and_text_question'   : 'ابتدا صورت سوال را ارسال نمایید، یا یک متن بنویسید، یا عکسی با کپشن ارسال نمایید',
    'get_option1'               : 'گزینه اول را وارد نمایید',
    'get_option2'               : 'گزینه دوم را وارد نمایید',
    'get_option3'               : 'گزینه سوم را وارد نمایید',
    'get_option4'               : 'گزینه چهارم را وارد نمایید',
    'get_optionanswer'          : 'گزینه صحیح را وارد نمایید',
    'get_textanswer'            : 'پاسخ تشریحی سوال را وارد کنید، یا به صورت متن یا به صورت یک عکس',
    'questoin_added'            : 'سوال مورد نظر در دیتابیس ذخیره شد',
}